version: "3.8"
services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_ARTIFACT_ROOT=/mlflow
      - MLFLOW_SQLITE_DB=/mlflow/mlflow.db
    volumes:
      - mlflow_data:/mlflow
    networks:
      - app_network

volumes:
  mongodb_data:
  mlflow_data:

networks:
  app_network:
    driver: bridge