FROM python:3.11-slim

# Install curl
RUN apt-get update && apt-get install -y curl

# Install MLflow
RUN pip install mlflow

# Expose the MLflow server port
EXPOSE 5000

# Set the default command to start the MLflow server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]