name: Python CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black bandit  # Install linting, formatting, and security tools

      # - name: Run Black (Formatter)
      #   run: |
      #     black .

      # - name: Run Flake8 (Linter)
      #   run: |
      #     flake8 .

      # - name: Run Bandit (Security)
      #   run: |
      #     bandit -c .bandit -r .

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start services with Docker Compose
        run: |
          docker-compose up --build -d

      - name: Check FastAPI logs
        run: |
          docker-compose logs fastapi

      - name: Wait for MongoDB to be ready
        run: |
          docker-compose exec -T mongodb mongo --eval 'db.runCommand("ping").ok'

      - name: Wait for FastAPI to be ready
        run: |
          until docker-compose exec -T fastapi curl -f http://localhost:8000/health; do
            echo "Waiting for FastAPI to be ready..."
            sleep 5
          done

      - name: Run tests
        run: |
          PYTHONPATH=$(pwd) pytest tests/

      - name: Stop services
        if: always()
        run: |
          docker-compose down

  build-and-push:
    runs-on: ubuntu-latest
    needs: test  # Ensure this job runs only if the test job is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-app:latest

  notify:
    runs-on: ubuntu-latest
    needs: [test, build-and-push]
    if: always()
    steps:
      - name: Send success email notification
        if: success()
        run: |
          curl -X POST "https://api.mailjet.com/v3.1/send" \
          -H "Content-Type: application/json" \
          -u "${{ secrets.MAILJET_API_KEY }}:${{ secrets.MAILJET_API_SECRET }}" \
          -d '{
                "Messages": [{
                  "From": {
                    "Email": "${{ secrets.EMAIL_SENDER }}",
                    "Name": "GitHub Actions"
                  },
                  "To": [{
                    "Email": "${{ secrets.EMAIL_RECIPIENT2 }}",
                    "Name": "Firas Aguech"
                  }],
                  "Subject": "GitHub Actions Workflow Status: Success",
                  "TextPart": "The GitHub Actions workflow has completed successfully!\n\nDetails:\n- Repository: ${{ github.repository }}\n- Commit: ${{ github.sha }}\n- Tests: Passed\n- Linting: Passed\n- Formatting: Passed\n- Security: Passed\n- Docker Build: Successfully Built and Pushed\n\nThank you for using our CI/CD pipeline."
                }]
              }'

      - name: Send failure email notification
        if: failure()
        run: |
          curl -X POST "https://api.mailjet.com/v3.1/send" \
          -H "Content-Type: application/json" \
          -u "${{ secrets.MAILJET_API_KEY }}:${{ secrets.MAILJET_API_SECRET }}" \
          -d '{
                "Messages": [{
                  "From": {
                    "Email": "${{ secrets.EMAIL_SENDER }}",
                    "Name": "GitHub Actions"
                  },
                  "To": [{
                    "Email": "${{ secrets.EMAIL_RECIPIENT2 }}",
                    "Name": "Firas Aguech"
                  }],
                  "Subject": "GitHub Actions Workflow Status: Failure",
                  "TextPart": "The GitHub Actions workflow has encountered an issue.\n\nDetails:\n- Repository: ${{ github.repository }}\n- Commit: ${{ github.sha }}\n- Tests: Failed or Skipped\n- Linting: Failed\n- Formatting: Failed\n- Security: Failed\n- Docker Build: Failed\n\nFor more information, please review the GitHub Actions logs or contact the team."
                }]
              }'