name: Python CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start services with Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for MongoDB to be ready
        run: |
          docker-compose exec -T mongodb mongo --eval 'db.runCommand("ping").ok'

      - name: Run tests
        run: |
          PYTHONPATH=$(pwd) pytest tests/

      - name: Stop services
        if: always()
        run: |
          docker-compose down

  build-and-push:
    runs-on: ubuntu-latest
    needs: test  # Ensure this job runs only if the test job is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-app:latest

  notify:
    runs-on: ubuntu-latest
    needs: [test, build-and-push]
    if: always()
    steps:
      - name: Send success email notification
        if: success()
        run: |
          curl -X POST "https://api.mailjet.com/v3.1/send" \
          -H "Content-Type: application/json" \
          -u "${{ secrets.MAILJET_API_KEY }}:${{ secrets.MAILJET_API_SECRET }}" \
          -d '{
                "Messages": [{
                  "From": {
                    "Email": "${{ secrets.EMAIL_SENDER }}",
                    "Name": "GitHub Actions"
                  },
                  "To": [{
                    "Email": "${{ secrets.EMAIL_RECIPIENT2 }}",
                    "Name": "Firas Aguech"
                  }],
                  "Subject": "GitHub Actions Workflow Status: Success",
                  "TextPart": "The GitHub Actions workflow has completed successfully!\n\nAll tests have passed, and the Docker image was built and pushed to Docker Hub without issues.\n\nWorkflow Summary:\n- Tests: Passed\n- Docker Image: Successfully Built and Pushed\n- Repository: ${{ github.repository }}\n- Commit: ${{ github.sha }}\n\nThank you for using our CI/CD pipeline."
                }]
              }'

      - name: Send failure email notification
        if: failure()
        run: |
          curl -X POST "https://api.mailjet.com/v3.1/send" \
          -H "Content-Type: application/json" \
          -u "${{ secrets.MAILJET_API_KEY }}:${{ secrets.MAILJET_API_SECRET }}" \
          -d '{
                "Messages": [{
                  "From": {
                    "Email": "${{ secrets.EMAIL_SENDER }}",
                    "Name": "GitHub Actions"
                  },
                  "To": [{
                    "Email": "${{ secrets.EMAIL_RECIPIENT2 }}",
                    "Name": "Firas Aguech"
                  }],
                  "Subject": "GitHub Actions Workflow Status: Failure",
                  "TextPart": "The GitHub Actions workflow has encountered an issue.\n\nUnfortunately, the tests or the Docker build/push process failed. Please review the logs below for detailed error messages and context.\n\nWorkflow Summary:\n- Tests: Failed or Skipped\n- Docker Build: Failed\n- Repository: ${{ github.repository }}\n- Commit: ${{ github.sha }}\n\nFor more information, please visit the GitHub Actions logs or contact the team."
                }]
              }'